spring:
  application:
    name: gradebook
  profiles:
    active: local
  mvc:
    log-resolved-exception: true
  datasource:
    url: jdbc:sqlite:sample.db
    username: admin
    password: admin
    driverClassName: org.sqlite.JDBC
  jpa:
    hibernate.ddl-auto: create
    hibernate.database-platform: org.sqlite.hibernate.dialect.SQLiteDialect


logging:
  level:
    com.coding.gradebook: INFO
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: ERROR